project:
  type: website
execute:
  freeze: auto
website:
  other-links:
     - text: Annexes
       icon: file-bar-graph
       href: annexes.html
     - text: Historique des changements
       icon: newspaper
       href: NEWS.html
     - text: Séminaire Lunch OFCE
       icon: file-earmark-easel
       href: seminaire_lunch_OFCE.html
     - text: Séminaire IRES-OFCE
       icon: file-earmark-easel
       href: seminaire_IRES_OFCE.html
     - text: Post sur le blog de l'OFCE
       icon: pen
       href: https://www.ofce.sciences-po.fr/blog2024/fr/2025/20251128_XT/
  title: "Partage de la valeur ajoutée, comparaisons internationales"
  page-navigation: true
  site-url: "https://xtimbeau.github.io/travail/"
  repo-url: "https://github.com/xtimbeau/travail/"
  reader-mode: false
  bread-crumbs: true
  favicon: www/fofce.png
  page-footer:
      border: true
      left: "![](/www/ccby4.png){height='16'}"
      right: "propulsé par ![](/www/quarto.png){height='16'}"
  navbar:
    title: false
    search: true
    code-tools: true
    bakground: "#FEFEFE"
    logo: www/ofce_m.png
    logo-alt: "OFCE"
    logo-href: "https://www.ofce.fr/"
    left:
      - text: "wp 2025-23"
        icon: house
        href: index.html
      - text: "Annexes"
        icon: file-bar-graph
        href: annexes.html
      - text: Historique
        icon: newspaper
        href: NEWS.html
    right:
      - text: " "
        icon: person-circle
        href: about.html
      - text: " "
        icon: github
        href: https://github.com/xtimbeau/travail
comments:
  hypothesis: true
format:
  ofce-html:
    link-external-icon: true
    smooth-scroll: true

language:
  fr:
    other-links-title: "Autres contenus"

wp: 23
annee: 2025
bibliography: references.bib
date: "2025-10-24"
date-modified: now

author:
  - name: "Xavier Timbeau"
    email: "xavier.timbeau@sciencespo.fr"
    affiliation: OFCE, Sciences Po Paris
    affiliation-url: "http://www.ofce.fr"
    orcid: "0000-0002-6198-5953"
