project:
  type: website
execute:
  freeze: auto
website:
  other-links:
     - text: Séminaire Lunch OFCE
       icon: file-earmark-easel
       href: seminaire_lunch_OFCE.html
  title: "Partage de la valeur ajoutée, comparaisons internationales"
  page-navigation: true
  site-url: "https://xtimbeau.github.io/travail/"
  repo-url: "https://github.com/xtimbeau/travail/"
  reader-mode: false
  bread-crumbs: true
  favicon: www/fofce.png
  page-footer:
      border: true
      left: "![](/www/ccby4.png){height='16'}"
      right: "propulsé par ![](/www/quarto.png){height='16'}"
  navbar:
    title: false
    search: true
    code-tools: true
    bakground: "#FEFEFE"
    logo: www/ofce_m.png
    logo-alt: "OFCE"
    logo-href: "https://www.ofce.fr/"
    right:
      - text: " "
        icon: person-circle
        href: about.html
      - text: " "
        icon: github
        href: https://github.com/xtimbeau/travail

comments:
  hypothesis: true
format:
  ofce-html: default

